### ISSUE TITLE
After loading a session, adding plots does not work

### ISSUE THREAD

**Issue by doc-l2** [NLeSC/spot-server#19]
Steps to reproduce:

1. Open a session (eg http://spot.phenomldata.org/#session=https://s3-eu-west-1.amazonaws.com/www.phenomldata.org/session_susyai.json)
2. Add a plot (eg bar plot of some variable)
3. Note it doesn't work
4. Refresh the page
5. Manually select dataset
6. Add the same plot of step 2
7. Note it works

Video:

https://www.youtube.com/watch?v=vIbbGNEIZfk

I can reproduce this issue with any dataset and any plot variable

**Comment by fdiblen** [comment]
Thank you for reporting. I could recreate the issue.

**Comment by fdiblen** [comment]
fixed in https://github.com/NLeSC/spot master branch
