### ISSUE TITLE
Not possible to import file when a column contains a space, dash or other non-alphanum char

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#4]
The only allowed characters are [a-zA-Z0-9\_]

Possible because the SQL that adds the columns doesn't put a quote around them? This makes it hard to create human-readable column names (or use MathJax for Latex).

**Comment by fdiblen** [comment]
@l-hendriks Can we close this issue?

**Comment by l-hendriks** [comment]
yeah it's basically a duplicate of #14
