### ISSUE TITLE
Not possible to import 2 datasets in 1 session (can fix manually)

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#5]
Creating a dataset in a new session works, but adding a second dataset doesn't. The dataset is added and the record is created in the session file, but no facets are created (that array is empty). This happens if I first upload A and then B, or first B and then A.

I can fix it by adding both A and B in new session, and then manually merge them in a new json and load that

**Comment by jiskattema** [comment]
Should be fixed now
