### ISSUE TITLE
When adding a second dataset to a config.json, the dataset facets are empty

### ISSUE THREAD

**Issue by l-hendriks** [NLeSC/spot-server#8]
Steps to reproduce: add a dataset using spot-import. Then add another dataset using spot-import using the same config.json. Spot-import should merge the datasets into 1 json file, but the facets array of the second set is empty.

The only way I can now have multiple datasets in, is to use a new config.json file every time and merge them manually

**Comment by fdiblen** [comment]
fixed in latest dev version.
